services:
  notification-system-db:
    container_name: notification-system-db
    #docker image to be used
    image: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
      # Where our data will be persisted
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - notification-system-db:/var/lib/mysql
        - ./init/init.sql:/docker-entrypoint-initdb.d/init-script.sql
    expose:
        # Opens port 3306 on the container
        - '3306'
    restart: always

volumes:
  notification-system-db:

