services:
  notification-system-db:
    container_name: notification-system-db
    image: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - notification-system-db:/var/lib/mysql
        - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
        # Opens port 3306 on the container
        - '3306'
    restart: always
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411

volumes:
  notification-system-db:

